### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by David-Klemenc** [sporto/elm-patterns#15]
On phantom types:
https://github.com/sporto/elm-patterns/blob/297bbaa57457a7385738636df5573ead11989a1a/docs/advanced/phantom-types.html#L181

> <p><code>activeUsers</code> is a function that only takes all users and returns only active users.</p>

The first "only" should be omitted:

> <p><code>activeUsers</code> is a function that takes all users and returns only active users.</p>

**Comment by sporto** [comment]
Fixed, thanks
