### ISSUE TITLE
Would "avoid boolean ambiguity" be a good pattern?

### ISSUE THREAD

**Issue by andreacfromtheapp** [sporto/elm-patterns#17]
Hi :)

I'm still learning with Elm in Action, and I've only made a [learning project](https://github.com/gacallea/elm_speakandspell) so far. So please excuse if this is not a pattern or it's inappropriate. Should this fit, it would make a great addition: "[Solving the Boolean Identity Crisis](https://www.youtube.com/watch?v=6TDKHGtAxeg)" by Jeremy Fairbank.

It boils down to be more specific about True/False values and only use a Bool when strictly necessary. Else use Types to make code clearer and making sense of "an opaque logic". I applied this to the sound control of to the [SpeechSynthesis](https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis) Web API.

Elm code in ```Main.elm```:

```elm
type Msg
    = ...
    ...
    | SetSound Sound
```

```elm
type Sound
    = On
    | Off
```

```elm
type alias Model =
    { ...
    , sound : Sound
      ...
    }
```

```elm
initialModel : Model
initialModel =
    { ...
    , sound = On
      ...
    }
```

```elm
        ...
        , button [ onClick (SetSound On) ] [ text "Sound On" ]
        , button [ onClick (SetSound Off) ] [ text "Sound Off" ]
        ...
```

```elm
update msg model =
    case msg of
        SetSound param ->
            ( model, setSound param)
```

```elm
setSound : Sound -> Cmd Msg
setSound switch =
    case switch of
        On ->
            sound True

        Off ->
            sound False
```

```elm
port sound : Bool -> Cmd msg
```

JavaScript code in ```index.html```

```javascript

      ...

      // Pause/Resume Speech Synth API (SetSound On | Off)
      app.ports.sound.subscribe(function (message) {
        synth.cancel();
        if (message == true) {
          synth.resume();
        } else {
          synth.pause();
        }
      });

      ...

```

I hope this makes sense, and I invite everyone reading this to watch Jeremy's video and rationale. It is amazing.

Should this idea be viable, and if necessary, I could come up with a PR.

Cheers

**Comment by sporto** [comment]
This is a great suggestion. I don't think is covered in the other patterns. A PR would be most welcome. Thanks

**Comment by sporto** [comment]
Done via https://github.com/sporto/elm-patterns/pull/18
