### ISSUE TITLE
Pattern ideas: I wonder if any of these can qualify as pattern

### ISSUE THREAD

**Issue by lucamug** [sporto/elm-patterns#24]
I wonder if any of these can qualify as pattern

<img width="845" alt="Screenshot 2023-02-23 at 21 00 37" src="https://user-images.githubusercontent.com/5551094/220900165-d0a1e3fc-6adc-4b06-8435-47cd2cae2f32.png">

**Comment by sporto** [comment]
Looks like a good pattern to cover: **conditional rendering**. Seems to be a common question. 

- Using a list of Maybes. 

- concatenating lists:

```
[ headerElement ]  ++ maybeBanner ++ [ bodyElement, footerElement ]
```

- using a noop:

```
[
  headerElement,
  if ... then bannerElement else text "",
  bodyElement
]
```

**Comment by sporto** [comment]
Added in http://sporto.github.io/elm-patterns/basic/conditional-rendering.html
