### ISSUE TITLE
Improve Process flow using phantom types

### ISSUE THREAD

**Issue by timmi-on-rails** [sporto/elm-patterns#28]
The described flows in https://sporto.github.io/elm-patterns/advanced/flow-phantom-types.html#process-flow-using-phantom-types are not safe:

For example leaving out `setTotal` would be fine in:

```elm
flowPrioritizingTotal : Int -> Order -> Order
flowPrioritizingTotal total order =
    Step order
        -- |> setTotal total
        |> adjustQuantityFromTotal
        |> done
```

although the flow is incomplete.

I propose to fix this with a `start` function as follows:

```elm
start : Order -> Step Start
start order = Step order
```
and a fixed flow:

```elm
flowPrioritizingTotal : Int -> Order -> Order
flowPrioritizingTotal total order =
    start order
        |> setTotal total
        |> adjustQuantityFromTotal
        |> done
```

Leaving out `setTotal` would now lead to a compile error as expected.

I have created a rather incomplete PR (which does not cover documentation and Ellie example) here: https://github.com/sporto/elm-patterns/pull/27

Thank you for your work!

**Comment by sporto** [comment]
Yes, that makes sense. Thanks for the PR

**Comment by timmi-on-rails** [comment]
So, here is the missing documentation and Ellie update.
I have added blank lines to match your code style and make sure the Ellie is identical to the code file in repo.

https://github.com/sporto/elm-patterns/pull/29
