### ISSUE TITLE
"Defective" example in pipeline isn't defective

### ISSUE THREAD

**Issue by jhbrown94** [sporto/elm-patterns#7]
On this page,
http://sporto.github.io/elm-patterns/advanced/pipeline-builder.html 
this is given as a defective example:
``` 
Ok User
        |> validateEmail user.email
        |> validateName user.name
```

I think the intention was to have something like this instead:
```
 Ok User
        |> validateName user.email
        |> validateEmail user.name
```

**Comment by sporto** [comment]
Thanks. I had a look, the example is fine. I updated the text to make it obvious what the problem is.

**Comment by jhbrown94** [comment]
Thank you.  I apologize for my conceptual biff.
