### ISSUE TITLE
In addition to package APIs, opaque types are useful for preserving representation invariants

### ISSUE THREAD

**Issue by jhbrown94** [sporto/elm-patterns#8]
The section on Opaque Types http://sporto.github.io/elm-patterns/advanced/opaque-types.html  presents them as principally useful for packages.  But I think the most useful part of opaque types is making it possible to ensure a representation invariant.  For instance, a type `SortedList` would benefit from being opaque -- if its internals were exposed, user code could modify the underlying representation and break the "sorted" invariant.  I think this is more important, for most people, than the package API stability argument.

**Comment by sporto** [comment]
This is a really good point, deserve more explanation. Will add something about this.

**Comment by sporto** [comment]
Added some content to this page and new page http://sporto.github.io/elm-patterns/advanced/opaque-types-invariants.html
I think this covers that. Feedback welcome. Thanks.

**Comment by jhbrown94** [comment]
Looks generally good.  One thought -- letting `add` take the sort routine allows for a malicious/confused caller to provide different sorts at different times.  If you wanted to go simple, you could limit the example to `comparable`s.  Alternately, you could store the sort function in the `SortedList` representation, but then you have a function in a datatype which is considered by many (but not me!) to be an anti-pattern.

**Comment by sporto** [comment]
I will prefer to have the simplest example as possible. So using comparable sounds good.
