### ISSUE TITLE
Consider adding the Effect pattern?

### ISSUE THREAD

**Issue by jhbrown94** [sporto/elm-patterns#9]
You've got a section on the `Action` pattern, but the `Effect` pattern is also nice and creates some improved testability.   http://reasonableapproximation.net/2019/10/20/the-effect-pattern.html

Also recently discussed on slack at the the sadly transient https://elmlang.slack.com/archives/C0CJ671HU/p1597424308223600

**Comment by sporto** [comment]
Yes, I will like to add it

**Comment by sporto** [comment]
Added
